run:
  timeout: 5m
  go: '1.23'

linters:
  enable-all: true
  disable:
    - gci
    - godot
    - wsl
    - testpackage
    - varnamelen
    - tagliatelle
    - nlreturn
    - mnd
    - exhaustruct
    - exportloopref
    - revive
    - forbidigo
    - depguard
    - ireturn

linters-settings:
  lll:
    line-length: 150
  gocyclo:
    min-complexity: 15
  funlen:
    lines: 80
    statements: 40
  nestif:
    min-complexity: 40

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
