services:
  # Syncoor centralized server
  syncoor-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syncoor-server
    ports:
      - "${SYNCOOR_SERVER_PORT:-10001}:8080"
    command: [
      "server",
      "--listen", ":8080",
      "--auth-token", "${SYNCOOR_AUTH_TOKEN:-}",
      "--log-level", "${LOG_LEVEL:-info}",
      "--mock"
    ]
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SYNCOOR_AUTH_TOKEN=${SYNCOOR_AUTH_TOKEN:-}
    networks:
      - syncoor-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Syncoor run
  syncoor-run:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syncoor-run
    depends_on:
      - syncoor-server
    command: [
      "sync",
      "--network", "${NETWORK:-hoodi}",
      "--el-client", "${EL_CLIENT:-geth}",
      "--cl-client", "${CL_CLIENT:-teku}",
      "--server", "http://host.docker.internal:${SYNCOOR_SERVER_PORT:-10001}",
      "--server-auth", "${SYNCOOR_AUTH_TOKEN:-}",
      "--log-level", "${LOG_LEVEL:-info}",
      "--report-dir", "/app/reports",
      "--label", "environment=local"
    ]
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SYNCOOR_AUTH_TOKEN=${SYNCOOR_AUTH_TOKEN:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp:/tmp
      - ${HOME}/.docker:/root/.docker:ro
      - ./reports:/app/reports
    network_mode: host
    restart: "no"  # Don't restart sync tests automatically

  # Syncoor report index generator
  syncoor-report-index-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syncoor-report-index-generator
    command: [
      "report-index",
      "--watch",
      "--report-dir", "/app/reports",
      "--output", "/app/reports/index.json",
      "--log-level", "${LOG_LEVEL:-info}"
    ]
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./reports:/app/reports
    networks:
      - syncoor-net
    restart: unless-stopped

  # Syncoor web UI
  syncoor-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: syncoor-web
    ports:
      - "${SYNCOOR_WEB_PORT:-10002}:80"
    environment:
      - SYNCOOR_WEB_PORT=${SYNCOOR_WEB_PORT:-10002}
    entrypoint: ["/bin/sh", "-c"]
    command:
    - >-
      echo '{
        "directories": [
          {
            "name": "Local Dev",
            "url": "http://localhost:'${SYNCOOR_WEB_PORT:-10002}'/reports/",
            "enabled": true
          },
          {
            "name": "Mock Reports",
            "url": "http://localhost:'${SYNCOOR_WEB_PORT:-10002}'/reports/mock/",
            "enabled": true
          }
        ],
        "syncoorApiEndpoints": [
          {
            "name": "Local Syncoor",
            "url": "http://localhost:${SYNCOOR_SERVER_PORT:-10001}",
            "enabled": true
          }
        ]

      }' > /usr/share/nginx/html/config.json &&
      nginx -g 'daemon off;'
    volumes:
      - ./reports:/usr/share/nginx/html/reports:ro
    networks:
      - syncoor-net
    restart: unless-stopped
    depends_on:
      - syncoor-server

networks:
  syncoor-net:
    driver: bridge
