services:
  # Syncoor centralized server
  syncoor-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syncoor-server
    ports:
      - "10001:8080"
    command: ["server", "--listen", ":8080", "--auth-token", "${SYNCOOR_AUTH_TOKEN:-}", "--log-level", "${LOG_LEVEL:-info}"]
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SYNCOOR_AUTH_TOKEN=${SYNCOOR_AUTH_TOKEN:-}
    volumes:
      - ./logs:/app/logs
    networks:
      - syncoor-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Sync client
  syncoor-client-hoodi-geth-teku:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syncoor-client
    depends_on:
      - syncoor-server
    command: [
      "sync",
      "--network", "${NETWORK:-hoodi}",
      "--el-client", "${EL_CLIENT:-geth}",
      "--cl-client", "${CL_CLIENT:-teku}",
      "--server", "http://host.docker.internal:8080",
      "--server-auth", "${SYNCOOR_AUTH_TOKEN:-}",
      "--log-level", "${LOG_LEVEL:-info}",
      "--report-dir", "/app/reports"
    ]
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SYNCOOR_AUTH_TOKEN=${SYNCOOR_AUTH_TOKEN:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/.docker:/root/.docker:ro
      - ./reports:/app/reports
    network_mode: host
    restart: "no"  # Don't restart sync tests automatically

  # Syncoor report index generator
  syncoor-report-index-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syncoor-index-generator
    entrypoint: ["/bin/sh", "-c"]
    command:
    - >-
      while true; do
        syncoor report-index --report-dir /app/reports --output /app/reports/index.json --log-level ${LOG_LEVEL:-info};
        sleep 60;
      done
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./reports:/app/reports
    networks:
      - syncoor-net
    restart: unless-stopped


  # Nginx web server for serving reports
  nginx-reports:
    image: nginx:alpine
    container_name: syncoor-nginx-reports
    ports:
      - "10002:80"
    volumes:
      - ./reports:/usr/share/nginx/html:ro
    networks:
      - syncoor-net
    restart: unless-stopped

networks:
  syncoor-net:
    driver: bridge
