name: Check - PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  merge_group:

concurrency:
  group: "title-checker-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

permissions:
  pull-requests: read

jobs:
  pr_title_checker:
    name: validate
    # Skip merge-queue PRs
    if: contains(github.ref_name, 'gh-readonly-queue/main/') != true
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@fdd4d3ddf614fbcd8c29e4b106d3bbe0cb2c605d # v6.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
