name: Syncoor - Matrix Test

on:
  workflow_dispatch:
    inputs:
      run-timeout:
        description: 'Timeout for the sync test'
        required: false
        default: '60m'
        type: string
      network:
        description: 'Network to test'
        required: false
        default: 'hoodi'
        type: string

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        el-client: [geth, besu, nethermind, erigon, reth]
        cl-client: [lighthouse, teku, prysm, nimbus, lodestar, grandine]
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'full-sync-test.yaml',
              ref: context.ref,
              inputs: {
                network: '${{ inputs.network || 'hoodi' }}',
                'el-client': '${{ matrix.el-client }}',
                'cl-client': '${{ matrix.cl-client }}',
                'run-timeout': '${{ inputs.run-timeout || '60m' }}'
              }
            });
